server:
  port: 8080
  servlet:
    context-path: /api

spring:
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update # create
      enable_lazy_load_no_trans: true # lazy loading
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non_contextual_creation: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/paf2023"
    username: paf2023
    password: paf2023
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  sql:
    init:
      platform: postgres

logging.level.org:
  springframework: INFO
  springframework.web: DEBUG
  springframework.jpa: TRACE
  hibernate: INFO


project-name: PaF 2023
#product.persistence.class: ProductFilePersistence
product.persistence.class: ProductDBPersistence
startup.print: true

